### ISSUE TITLE
Enable m4a support

### ISSUE THREAD

**Issue by taynaron** [Nianna/Karedi#38]
Many newer Ultrastar files are tied to m4a files instead of mp3. Is there a way to add m4a support to Karedi?

**Comment by Nianna** [comment]
Not sure. It entirely depends on whether there is some existing java library that can load such files and allows random access - meaning it can play any chosen short fragment of the song over and over again with sufficient accuracy.

If anyone can recommend such library, please do so.

**Comment by Nianna** [comment]
Ok, good news - I've managed to make it work.

There are still some tests and improvements required, but I will add it as a beta feature in the next Karedi version.

**Comment by taynaron** [comment]
Oh hooray! Thank you!
