### ISSUE TITLE
Enable ogg Support. Melody Mania

### ISSUE THREAD

**Issue by jimmyhawkin** [Nianna/Karedi#39]
Hi! please add OGG support as mp3 is more and more not being used as mainstream. Melody mania even suggests it as it works best with the engine it uses.

**Comment by Nianna** [comment]
Similar to issue #38 . I would love to add support for other audio formats, but to do so, I preferably need some existing free java library that can load such files and that allows random access - meaning it can play any chosen short fragment of the song over and over again with sufficient accuracy.

If anyone can recommend such library, please do so.

**Comment by Nianna** [comment]
Good news, I've managed to make it work so next Karedi release will have OGG support as beta feature.
